site_name: Voleer Developer

nav:
  - Home: index.md
  - About:
      - 'About Voleer.md': about.md
      - 'BitTitan': bittitan.md
  - Getting started:
      - signup.md
      - install-cli.md
  - Reference:
      - license.md
      - Markdown:
        - md/basic.md
        - md/advanced.md
      - Voleer CLI:
        - cli/overview.md
        - cli/login.md
      

theme:
  name: material
  # custom_dir: overrides  

  palette:
    scheme: preference # default | slate
    primary: blue grey # indigo | blue

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    # - toc.integrate # Display TOC on the left if space allows
  # Insiders only
  # features:
  #   - search.highlight

    # - header.autohide # Automatically hide header after certain threshold

  logo: images/logo-blue.png
  favicon: images/favicon-32x32.ico

extra_css:
  - css/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight      
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/voleer
      name: Voleer on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/voleer
      name: Voleer on GitHub

copyright: Copyright &copy; 2021 BitTitan, Inc.

repo_url: https://github.com/voleer/sdk-docs-test
repo_name: voleer/sdk-docs-test
edit_uri: edit/main/docs/