site_name: Voleer Developer

nav:
  - Home: index.md
  - About:
      - 'About Voleer.md': about.md
      - 'BitTitan': bittitan.md
  - Getting started:
      - signup.md
      - install-cli.md
  - Reference:
      - 'Technical example': example.md
      - license.md
      - Voleer CLI:
        - cli/overview.md
        - cli/login.md

theme:
  name: material
  # custom_dir: overrides  

  palette:
    scheme: preference # default | slate
    primary: blue grey # indigo | blue

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    # - toc.integrate # Display TOC on the left if space allows
  # Insiders only
  # features:
  #   - search.highlight

    # - header.autohide # Automatically hide header after certain threshold

  logo: images/logo-blue.png
  favicon: images/favicon-32x32.ico

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  # - pymdownx.highlight
  # - pymdownx.superfences

# markdown_extensions:
#   - pymdownx.highlight
#   - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/voleer
      name: Voleer on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/voleer
      name: Voleer on GitHub

copyright: Copyright &copy; 2021 BitTitan, Inc.

repo_url: https://github.com/voleer/sdk-docs-test
repo_name: voleer/sdk-docs-test